### ISSUE TITLE
work with styled-components

### ISSUE THREAD

**Issue by rifler** [eprincev-egor/no-cyrillic-string#2]
```js
import styled from 'styled-components';

const Component = styled.div`
    /* комментарий на русском */
    // комментарий на русском
    color: red;
`;
```

I understand that plugin works as expected, but maybe you have some thoughts how it can be fixed?

**Comment by eprincev-egor** [comment]
Лень переводить на английский. Думаю распарить комментарии внутри литерала строки можно. Но чутье подсказывает, что не стоит этого делать. Только если другое правило писать или настройку для этого правила передавать. Если сильно надо, то ок. Если нет, то советую просто добавить eslint ignore next

**Comment by rifler** [comment]
согласен, добавил игнор на это правило через overrides по файловой маске `styles.tsx?`
